CREATE TABLE DATOSPERSONALES (
    DNI VARCHAR2(9) NOT NULL,
    NOMBRE VARCHAR2(32) NOT NULL,
    PRAPELLIDO VARCHAR2(32) NOT NULL,
    SGAPELLIDO VARCHAR2(32),
    DOMICILIO VARCHAR2 NOT NULL,
    TELEFONO NUMBER(12),
    CORREO VARCHAR2(12) NOT NULL,
    TIPO VARCHAR2(16)

);

ALTER TABLE DATOSPERSONALES {
    ADD CONSTRAINT DATOSPERSONALES_PK PRIMARY KEY (DNI)
    ADD CONSTRAINT DATOSPERSONALES_CK CHECK(TIPO IN(DIRECTOR,VENDEDOR,CLIENTE,COMERCIAL))
};

CREATE TABLE DIRECTOR (
    DNI VARCHAR2(9) NOT NULL
);

ALTER TABLE DIRECTOR {
    ADD CONSTRAINT DIRECTOR_PK PRIMARY KEY (DNI)
    ADD CONSTRAINT DIRECTOR_FK FOREIGN KEY (DNI)
     REFERENCE DATOSPERSONALES ( DNI )
};

CREATE TABLE COMERCIAL (
    DNI VARCHAR2(9) NOT NULL
);

ALTER TABLE COMERCIAL {
    ADD CONSTRAINT COMERCIAL_PK PRIMARY KEY (DNI)
    ADD CONSTRAINT COMERCIAL_FK FOREIGN KEY (DNI)
     REFERENCE DATOSPERSONALES ( DNI )
};

CRAETE TABLE OFICINA (
    CODOFICINA NUMBER NOT NULL;
    DIRECCION VARCHAR2(128) NOT NULL;
    DIRECTOR VARCHAR2(9) NOT NULL;
    COMERCIAL VARCHAR2(9) NOT NULL
);

ALTER TABLE OFICINA {
    ADD CONSTRAINT OFICINA_PK PRIMARY KEY (CODOFICINA)
    ADD CONSTRAINT OFICINA_DIR_FK FOREIGN KEY (DIRECTOR)
        REFERENCE DIRECTOR (DNI)
    ADD CONSTRAINT OFICINA_COM_FK FOREIGN KEY (COMERCIAL)
        REFERENCE COMERCIAL (DNI) 
};

CREATE TABLE VENDEDOR (
    DNI VARCHAR2(9) NOT NULL,
    TURNO VARCHAR2(16) NOT NULL,
    OFICINA NUMBER NOT NULL
);

ALTER TABLE VENDEDOR{
    ADD CONSTRAINT CHECK(TURNO IN(DIA,TARDE))
};